import type { XmlDocument } from "./document";

export type InferredElement = {
  name: string;
  count: number;
  children: { name: string; min: number; max: number }[];
  order: string[]; // first-seen child order (sequence)
  attrs: Map<string, { count: number; type: string }>;
  hasText: boolean;
  textType: string;
  parents: Set<string>;
};

/**
 * "Generate Schema from XML instance" (XMLSpy DTD/Schema ▸ Generate DTD/Schema).
 * Streams the structural index (bounded sample) — never a DOM.
 */
export async function inferSchema(doc: XmlDocument, sampleLimit = 100_000): Promise<Map<string, InferredElement>> {
  const ix = doc.index;
  const map = new Map<string, InferredElement>();
  const get = (n: string) => {
    let e = map.get(n);
    if (!e) {
      e = { name: n, count: 0, children: [], order: [], attrs: new Map(), hasText: false, textType: "xs:string", parents: new Set() };
      map.set(n, e);
    }
    return e;
  };
  const limit = Math.min(ix.elemDepth.length, sampleLimit);
  // per element: child name counts for min/max occurrence
  const childCounts = new Map<string, Map<string, number>>(); // parentName -> childName -> count for current instance
  for (let i = 0; i < limit; i++) {
    const name = ix.names[ix.elemName[i]];
    const e = get(name);
    e.count++;
    const p = ix.elemParent[i];
    if (p >= 0) {
      const pn = ix.names[ix.elemName[p]];
      e.parents.add(pn);
      const pe = get(pn);
      if (!pe.order.includes(name)) pe.order.push(name);
    }
  }
  // occurrence bounds: walk each parent's children lists (first 2,000 parents per name)
  const seenPerName = new Map<string, number>();
  for (let i = 0; i < limit; i++) {
    const name = ix.names[ix.elemName[i]];
    const seen = seenPerName.get(name) ?? 0;
    if (seen > 2000) continue;
    seenPerName.set(name, seen + 1);
    const e = get(name);
    const kids = doc.childrenOf(i, 5000);
    const counts = new Map<string, number>();
    for (const k of kids) {
      const kn = ix.names[ix.elemName[k]];
      counts.set(kn, (counts.get(kn) ?? 0) + 1);
    }
    for (const cn of e.order) {
      const c = counts.get(cn) ?? 0;
      let entry = e.children.find((x) => x.name === cn);
      if (!entry) {
        entry = { name: cn, min: seen === 0 ? c : 0, max: c };
        e.children.push(entry);
      } else {
        entry.min = Math.min(entry.min, c);
        entry.max = Math.max(entry.max, c);
      }
    }
    childCounts.set(name, counts);
  }
  // attributes & text types: sample up to 25 instances per element name
  const sampled = new Map<string, number>();
  for (let i = 0; i < limit; i++) {
    const name = ix.names[ix.elemName[i]];
    const s = sampled.get(name) ?? 0;
    if (s >= 25) continue;
    sampled.set(name, s + 1);
    const info = await doc.nodeInfo(i);
    const e = get(name);
    for (const [k, v] of info.attrs) {
      const a = e.attrs.get(k) ?? { count: 0, type: guessType(v) };
      a.count++;
      a.type = mergeType(a.type, guessType(v));
      e.attrs.set(k, a);
    }
    if (info.text) {
      e.hasText = true;
      e.textType = s === 0 ? guessType(info.text) : mergeType(e.textType, guessType(info.text));
    }
  }
  return map;
}

export function guessType(v: string): string {
  if (/^-?\d+$/.test(v)) return /^\d+$/.test(v) && v !== "0" && !v.startsWith("0") ? "xs:positiveInteger" : "xs:integer";
  if (/^-?\d*\.\d+$/.test(v)) return "xs:decimal";
  if (/^\d{4}-\d{2}-\d{2}$/.test(v)) return "xs:date";
  if (/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/.test(v)) return "xs:dateTime";
  if (/^(true|false)$/.test(v)) return "xs:boolean";
  if (/^https?:\/\//.test(v)) return "xs:anyURI";
  return "xs:string";
}
function mergeType(a: string, b: string) {
  if (a === b) return a;
  const nums = ["xs:positiveInteger", "xs:integer", "xs:decimal"];
  if (nums.includes(a) && nums.includes(b)) return nums[Math.max(nums.indexOf(a), nums.indexOf(b))];
  return "xs:string";
}

export function schemaToXsd(map: Map<string, InferredElement>, targetNs?: string): string {
  const roots = Array.from(map.values()).filter((e) => e.parents.size === 0);
  let out = `<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by XMLSpy-rs: DTD/Schema ▸ Generate Schema from XML instance (Venetian Blind design) -->\n<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"${targetNs ? ` targetNamespace="${targetNs}" xmlns="${targetNs}" elementFormDefault="qualified"` : ""}>\n`;
  const emitted = new Set<string>();
  const emit = (e: InferredElement, indent: string, global: boolean) => {
    const local = e.name.split(":").pop();
    if (global && emitted.has(e.name)) return;
    if (global) emitted.add(e.name);
    const simple = e.children.length === 0 && e.attrs.size === 0;
    if (simple) {
      out += `${indent}<xs:element name="${local}" type="${e.hasText ? e.textType : "xs:string"}"${global ? "" : occ(e, false)}/>\n`;
      return;
    }
    out += `${indent}<xs:element name="${local}"${global ? "" : occ(e, false)}>\n${indent}  <xs:complexType${e.hasText && e.children.length === 0 ? "" : e.hasText ? ' mixed="true"' : ""}>\n`;
    if (e.hasText && e.children.length === 0) {
      out += `${indent}    <xs:simpleContent><xs:extension base="${e.textType}">\n`;
      for (const [k, a] of e.attrs) out += `${indent}      <xs:attribute name="${k}" type="${a.type}"${a.count === Math.min(e.count, 25) ? ' use="required"' : ""}/>\n`;
      out += `${indent}    </xs:extension></xs:simpleContent>\n`;
    } else {
      if (e.children.length) {
        out += `${indent}    <xs:sequence>\n`;
        for (const c of e.children) {
          const ce = map.get(c.name)!;
          const cl = c.name.split(":").pop();
          const o = `${c.min === 1 ? "" : ` minOccurs="${c.min}"`}${c.max === 1 ? "" : ` maxOccurs="${c.max > 5 ? "unbounded" : c.max}"`}`;
          if (ce.children.length === 0 && ce.attrs.size === 0) out += `${indent}      <xs:element name="${cl}" type="${ce.hasText ? ce.textType : "xs:string"}"${o}/>\n`;
          else out += `${indent}      <xs:element ref="${cl}"${o}/>\n`;
        }
        out += `${indent}    </xs:sequence>\n`;
      }
      for (const [k, a] of e.attrs) out += `${indent}    <xs:attribute name="${k}" type="${a.type}"${a.count === Math.min(e.count, 25) ? ' use="required"' : ""}/>\n`;
    }
    out += `${indent}  </xs:complexType>\n${indent}</xs:element>\n`;
  };
  for (const r of roots) emit(r, "  ", true);
  for (const e of map.values()) if (!emitted.has(e.name) && (e.children.length || e.attrs.size)) emit(e, "  ", true);
  out += `</xs:schema>\n`;
  return out;
}
function occ(_e: InferredElement, _x: boolean) {
  return "";
}
