#!/usr/bin/env bash
# Build the Rust engine for the browser and embed it in the web app.
#
#   ./rust/build-wasm.sh            release build (default)
#   SIMD=1 ./rust/build-wasm.sh     enable wasm SIMD128 (needs Chrome 91+/FF 89+/Safari 16.4+)
#
# The .wasm is emitted as base64 inside src/engine/wasmBinary.ts so that
# vite-plugin-singlefile can keep producing ONE self-contained index.html and the
# Blob-URL worker can instantiate the module without a network fetch.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"

target=wasm32-unknown-unknown
out="$here/target/$target/wasm/xmlspy_wasm.wasm"
dest="$here/../XMLSpy/src/engine/wasmBinary.ts"

flags=""
if [[ "${SIMD:-0}" == "1" ]]; then
  flags="-C target-feature=+simd128"
  echo "· building with wasm simd128"
fi

RUSTFLAGS="$flags" cargo build --profile wasm --target "$target" -p xmlspy-wasm "${@}"

size=$(wc -c < "$out")
rustc_v=$(rustc --version | cut -d' ' -f2)
echo "· $out — $size bytes (rustc $rustc_v)"

node - "$out" "$dest" "$size" "$rustc_v" "${SIMD:-0}" <<'NODE'
const fs = require("fs");
const [, , wasmPath, dest, size, rustc, simd] = process.argv;
const b64 = fs.readFileSync(wasmPath).toString("base64");
const banner = `// @generated by rust/build-wasm.sh — DO NOT EDIT.
//
// The XMLSpy-rs engine (crates/xmlspy-{core,index,parse,wasm}) compiled to
// wasm32-unknown-unknown and inlined as base64 so the single-file bundle and the
// Blob-URL worker both work without an extra network request.
//
// Rebuild with:  npm run build:wasm
`;
const meta = `export const WASM_BUILD = {
  bytes: ${size},
  base64Bytes: ${b64.length},
  abi: 1,
  rustc: "${rustc}",
  simd128: ${simd === "1"},
  target: "wasm32-unknown-unknown",
  profile: "wasm (opt-level=2, lto=fat, panic=abort)",
} as const;
`;
fs.writeFileSync(dest, `${banner}\n${meta}\nexport const WASM_BASE64 =\n  "${b64}";\n`);
console.log(`· wrote ${dest} (${b64.length} base64 chars)`);
NODE
